ULLCost/Controllers/MoviesController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using ULLCost.Models;

namespace ULLCost.Controllers
{
    public class MoviesController : Controller
    {
        private readonly ULLCostContext _context;

        public MoviesController(ULLCostContext context)
        {
            _context = context;
        }

        // GET: Movies
      /*  public async Task<IActionResult> Index(string searchString)
        {
            var movies = from m in _context.Movie
                         select m;

            if (!String.IsNullOrEmpty(searchString))
            {
                movies = movies.Where(s => s.Level.Contains(searchString));
            }

            return View(await movies.ToListAsync());
        } */
        public ActionResult Index(string movieTerm, string movieLevel, string movieState, string movieGenre, int movieCredit, string searchString)
        {
            //Term Query
            var TermLst = new List<string>();

            var TermQry = from a in _context.Movie
                          orderby a.Term
                          select a.Term;
            TermLst.AddRange(TermQry.Distinct());
            ViewBag.movieTerm = new SelectList(TermLst);

            //Level Query
            var LevelLst = new List<string>();

            var LevelQry = from b in _context.Movie
                           orderby b.Level
                           select b.Level;
            LevelLst.AddRange(LevelQry.Distinct());
            ViewBag.movieLevel = new SelectList(LevelLst);

            //State Query
            var StateLst = new List<string>();

            var StateQry = from b in _context.Movie
                           orderby b.State
                           select b.State;
            StateLst.AddRange(StateQry.Distinct());
            ViewBag.movieState = new SelectList(StateLst);

            //Status Query
            var StatusLst = new List<string>();

            var StatusQry = from d in _context.Movie
                           orderby d.Status
                           select d.Status;
            StatusLst.AddRange(StatusQry.Distinct());
            ViewBag.movieGenre = new SelectList(StatusLst);

            //Credits Query
            var CreditLst = new List<int>();

            var CreditQry = from d in _context.Movie
                                              orderby d.Credits
                                              select d.Credits;
            CreditLst.AddRange(CreditQry.Distinct());
            ViewBag.movieCredit = new SelectList(CreditLst);
            string creditstring = movieCredit.ToString();

           
            var movies = from m in _context.Movie
                         select m;
            
            if (!String.IsNullOrEmpty(searchString))
            {
                movies = movies.Where(s => s.Level.Contains(searchString));
            }

            if (!string.IsNullOrEmpty(movieGenre))
            {
                movies = movies.Where(x => x.Status == movieGenre);
            }

            if (!string.IsNullOrEmpty(movieTerm))
            {
                movies = movies.Where(y => y.Term == movieTerm);
            }
            if (!string.IsNullOrEmpty(movieState))
            {
                movies = movies.Where(y => y.State == movieState);
            }
            if (!string.IsNullOrEmpty(creditstring))
            {
                movies = movies.Where(y => y.Credits == movieCredit);
            }

            if (!string.IsNullOrEmpty(movieLevel))
            {
                movies = movies.Where(z => z.Level == movieLevel);
            }

            return View(movies);
        }

        // GET: Movies/Details/5
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var movie = await _context.Movie
                .SingleOrDefaultAsync(m => m.ID == id);
            if (movie == null)
            {
                return NotFound();
            }

            return View(movie);
        }

        // GET: Movies/Create
        public IActionResult Create()
        {
            return View();
        }

        // POST: Movies/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("ID,Term,Level,State,Status,Credits,Fees")] Movie movie)
        {
            if (ModelState.IsValid)
            {
                _context.Add(movie);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(movie);
        }

        // GET: Movies/Edit/5
        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var movie = await _context.Movie.SingleOrDefaultAsync(m => m.ID == id);
            if (movie == null)
            {
                return NotFound();
            }
            return View(movie);
        }

        // POST: Movies/Edit/5
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("ID,Term,Level,State,Status,Credits,Fees")] Movie movie)
        {
            if (id != movie.ID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(movie);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!MovieExists(movie.ID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            return View(movie);
        }

        // GET: Movies/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var movie = await _context.Movie
                .SingleOrDefaultAsync(m => m.ID == id);
            if (movie == null)
            {
                return NotFound();
            }

            return View(movie);
        }

        // POST: Movies/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        {
            var movie = await _context.Movie.SingleOrDefaultAsync(m => m.ID == id);
            _context.Movie.Remove(movie);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }

        private bool MovieExists(int id)
        {
            return _context.Movie.Any(e => e.ID == id);
        }
    }
}

ULLCost/Views/Movies/Create.cshtml
@model ULLCost.Models.Movie

@{
    ViewData["Title"] = "Create";
}

<h2>Create</h2>

<h4>Movie</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Term" class="control-label"></label>
                <input asp-for="Term" class="form-control" />
                <span asp-validation-for="Term" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Level" class="control-label"></label>
                <input asp-for="Level" class="form-control" />
                <span asp-validation-for="Level" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="State" class="control-label"></label>
                <input asp-for="State" class="form-control" />
                <span asp-validation-for="State" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Status" class="control-label"></label>
                <input asp-for="Status" class="form-control" />
                <span asp-validation-for="Status" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Credits" class="control-label"></label>
                <input asp-for="Credits" class="form-control" />
                <span asp-validation-for="Credits" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Fees" class="control-label"></label>
                <input asp-for="Fees" class="form-control" />
                <span asp-validation-for="Fees" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

ULLCost/Views/Movies/Delete.cshtml
@model ULLCost.Models.Movie

@{
    ViewData["Title"] = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Movie</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Term)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Term)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Level)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Level)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.State)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.State)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Status)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Status)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Credits)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Credits)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Fees)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Fees)
        </dd>
    </dl>
    
    <form asp-action="Delete">
        <input type="hidden" asp-for="ID" />
        <input type="submit" value="Delete" class="btn btn-default" /> |
        <a asp-action="Index">Back to List</a>
    </form>
</div>

ULLCost/Views/Movies/Details.cshtml
@model ULLCost.Models.Movie

@{
    ViewData["Title"] = "Details";
}

<h2>Details</h2>

<div>
    <h4>Movie</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Term)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Term)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Level)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Level)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.State)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.State)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Status)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Status)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Credits)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Credits)
        </dd>
        <dt>
            @Html.DisplayNameFor(model => model.Fees)
        </dt>
        <dd>
            @Html.DisplayFor(model => model.Fees)
        </dd>
    </dl>
</div>
<div>
    <a asp-action="Edit" asp-route-id="@Model.ID">Edit</a> |
    <a asp-action="Index">Back to List</a>
</div>

ULLCost/Views/Movies/Edit.cshtml
@model ULLCost.Models.Movie

@{
    ViewData["Title"] = "Edit";
}

<h2>Edit</h2>

<h4>Movie</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="ID" />
            <div class="form-group">
                <label asp-for="Term" class="control-label"></label>
                <input asp-for="Term" class="form-control" />
                <span asp-validation-for="Term" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Level" class="control-label"></label>
                <input asp-for="Level" class="form-control" />
                <span asp-validation-for="Level" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="State" class="control-label"></label>
                <input asp-for="State" class="form-control" />
                <span asp-validation-for="State" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Status" class="control-label"></label>
                <input asp-for="Status" class="form-control" />
                <span asp-validation-for="Status" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Credits" class="control-label"></label>
                <input asp-for="Credits" class="form-control" />
                <span asp-validation-for="Credits" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Fees" class="control-label"></label>
                <input asp-for="Fees" class="form-control" />
                <span asp-validation-for="Fees" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

ULLCost/Views/Movies/Index.cshtml
@model IEnumerable<ULLCost.Models.Movie>
@{
    ViewData["Title"] = "Index";
}

<center>
    <h2 style="color:#800000">Cost Estimator</h2>
</center>
<!--
<p>
    <a asp-action="Create">Create New</a>
</p>
-->
<form asp-controller="Movies" asp-action="Index">
    <p>
        <table class="table">
           
            <tbody>
                <tr>
                    <td>
                        What term are you enrolling yourself for?
                    </td>
                    <td>
                        @Html.DropDownList("movieTerm", "All")
                    </td>

                </tr>
                <tr>
                    <td>
                        Are you a Graduate/Undergraduate student?
                    </td>
                    <td>
                        @Html.DropDownList("movieLevel", "All")
                    </td>
                </tr>
                <tr>
                    <td>
                        Are you a Resident/Non-Resident student?
                    </td>
                    <td>
                        @Html.DropDownList("movieState", "All")
                    </td>
                </tr>
                <tr>
                    <td>
                        Are you an International Student?
                    </td>
                    <td>
                        @Html.DropDownList("movieGenre", "All")
                    </td>
                </tr>
                <tr>
                    <td>
                        How many credits are you applying for?
                    </td>
                    <td>
                        @Html.DropDownList("movieCredit")
                    </td>
                </tr>
            </tbody>


        </table>

        <center>  <input class="button" type="submit" value="Estimate" /> </center>


        <!-- Level: <input type="text" name="SearchString"> -->
<br />
        <br />
        <br />

</form>
<table class="table">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Term)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Level)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.State)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Status)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Credits)
            </th>
            <th>
                $ @Html.DisplayNameFor(model => model.Fees)
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Term)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Level)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.State)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Status)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Credits)
            </td>
            <td>
               $ @Html.DisplayFor(modelItem => item.Fees)
            </td>
            <!--  <td>
            <a asp-action="Edit" asp-route-id="@item.ID">Edit</a> |
            <a asp-action="Details" asp-route-id="@item.ID">Details</a> |
            <a asp-action="Delete" asp-route-id="@item.ID">Delete</a>
        </td>
                -->
    </tr>
    }
        </tbody>
    </table>